version: '3'

services:
  app:
    image: node:20.9.0-alpine3.18
    ports:
      - 5173:5173
    volumes:
      - ./:/app/
    working_dir: /app
    command: npm run dev -- --host 0.0.0.0 --port 5173
